# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('start_date', models.DateField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
