# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vale',
            name='job_id',
            field=models.CharField(max_length=20),
        ),
    ]
